### ISSUE TITLE
Autenticação

### ISSUE THREAD

**Issue by leandrosouzadev** [jonathanmdr/Algafood-API#5]
Fala Jonathan. blz?

Sou novo no spring, e dando uma googlada acabei me deparando com o seu projeto. 

Vi que está usando OAuth2 e lendo banco de dados para pegar informações do usuário.... como seria a forma de fazer login pelo postman?

**Comment by jonathanmdr** [comment]
Olá @leandrosouzadev, tudo tranquilo e contigo?

Utilizando o fluxo de autenticação "**password flow**", basta informar na aba `Authorization` os dados do `client` (usuário/senha) que está cadastrado e autorizado a acessar a `API`, ou seja, inclusos na tabela `oauth_client_details` do banco de dados, a requisição utiliza o verbo `HTTP POST`, o corpo da requisição segue o formato `application/x-www-form-urlencoded`, além destas informações também deve ser fornecido no corpo da requisição os dados do usuário que está se autenticando (usuário/senha) e também o `grant_type` que define qual fluxo de autenticação do `OAuth2` estamos utilizando, neste caso informamos "`password`" pois estamos utilizando o "**password flow**".

Segue abaixo o curl de exemplo, caso queira importar em seu postman para um melhor entendimento!

```
curl --location --request POST 'http://localhost:8080/oauth/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic YWxnYWZvb2Qtd2ViOjEyMw==' \
--data-urlencode 'username=nomeDoSeuUsuarioCadastradoNoDB' \
--data-urlencode 'password=senhaDoSeuUsuarioCadastradoNoDB' \
--data-urlencode 'grant_type=password'
```

**Comment by leandrosouzadev** [comment]
Opa! tudo tranquilo por aqui!

Obrigado por responder!

Baixei seu projeto e rodei aqui, segui suas instruções e acabei enroscando nesse erro: 

> `Authentication failed: password does not match stored value
>  Authentication request for failed: org.springframework.security.authentication.BadCredentialsException: Bad credentials`

ja gerei varias vezes o password das tabelas oauth_client_details e usuario mas não consegui sair disso... tem alguma ideia?

**Comment by jonathanmdr** [comment]
Bad credential é algum problema com com as credenciais, ou de usuário, ou de clients!

As senhas que você está gerando para os mesmos é gerada com Bcrypt?

Eu utilizava este site aqui para gerar os hash's de senhas: https://bcrypt-generator.com/

**Comment by leandrosouzadev** [comment]
Deu certo brother! Acredito que o padrão das senhas estava incorreto mesmo. Obrigado pela força!!!
